name: MILL3 WP Theme boilerplate build test
on:
  push:
    branches:
      - master
      - vendor-less
jobs:
  Mill3-Deploy-Actions:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      THEME_PATH: "wp-content/themes/mill3-wp-theme-boilerplate/"
      WPENGINE_ENV_NAME: ${{ github.ref == 'refs/heads/master' && 'm3boilerplate' || 'm3boilerplastg' }}
      SITE_NAME: ":amazed_clap: Wordpress Theme Boilerplate :doatm: :hugz: :reno: :capiche:"
      PROD_SITE_URL: "https://m3boilerplastg.wpenginepowered.com/"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Copy env.production sample file to .env
        run: cp .env.production .env
      - name: Install Node dependencies
        run: npm ci
      - name: Webpack build command
        id: build
        run: npm run build
      - name: Install PHP dependencies
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "composer.json"
        with:
          php_version: "8.2"
          version: "2.2"
          args: "--ignore-platform-reqs"
          # working_dir: ${{ env.THEME_PATH }} # Uncomment if you need to run composer in a specific directory
      - name: Deploy to WPEngine
        if: ${{ success() }}
        uses: wpengine/github-action-wpe-site-deploy@v3.1.1
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ env.WPENGINE_ENV_NAME }}
          PHP_LINT: FALSE
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          CACHE_CLEAR: TRUE
          SRC_PATH: ./
          REMOTE_PATH: ${{ env.THEME_PATH }}
      - name: Notify to Slack
        if: ${{ success() }}
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#notifications'
          config: .github/slack.yml


